apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-infra
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest  # Vous pouvez changer cette image si nécessaire
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: my-app-config  # Utilisation du ConfigMap pour les variables d'environnement
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-app-secret  # Utilisation du Secret pour le mot de passe
              key: DB_PASSWORD
