version: '3.8'

services :
   db:
     image : mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
       MYSQL_DATABASE: testdb
     ports:
     -  "3306:3306"
     
     volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
      
         
      


  


      
